//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FF_Fastfood.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Banner
    {
        public int id { get; set; }
        public string bannerIMG { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public string linkURL { get; set; }
        public string seo_title { get; set; }
        public string seo_descript { get; set; }
        public string seo_keywords { get; set; }
        public string slug { get; set; }
        public Nullable<System.DateTime> start_Date { get; set; }
        public Nullable<System.DateTime> end_Date { get; set; }
    }
}
